// Generated by https://quicktype.io

export interface IWeatherResponse {
  status: string;
  count: string;
  info: string;
  infocode: string;
  lives?: ILife[];
  forecasts?: Forecast[];
}

export interface ILife {
  province: string;
  city: string;
  adcode: string;
  weather: string;
  temperature: string;
  winddirection: string;
  windpower: string;
  humidity: string;
  reporttime: string;
}


export interface Forecast {
  city: string;
  adcode: string;
  province: string;
  reporttime: string;
  casts: Cast[];
}

export interface Cast {
  date: string;
  week: string;
  dayweather: string;
  nightweather: string;
  daytemp: string;
  nighttemp: string;
  daywind: string;
  nightwind: string;
  daypower: string;
  nightpower: string;
}


